/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 02:10:49 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GenQueueTest_ESTest extends GenQueueTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[6];
      GenQueueTest.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GenQueueTest genQueueTest0 = new GenQueueTest();
  }
}
